templates:
  data-extraction:
    remote: data-extraction
    url: https://github.com/run-llama/template-workflow-data-extraction.git
    branch: main
    version: 0.1.7
  document-qa:
    remote: document-qa
    url: https://github.com/run-llama/template-workflow-document-qa.git
    branch: main
    version: 0.1.4
  basic-ui:
    remote: basic-ui
    url: https://github.com/run-llama/template-workflow-basic-ui.git
    branch: main
    version: 0.1.4
  basic:
    remote: basic
    url: https://github.com/run-llama/template-workflow-basic.git
    branch: main
    version: 0.1.0
  document-parsing:
    remote: document-parsing
    url: https://github.com/run-llama/template-workflow-document-parsing.git
    branch: main
    version: 0.1.0
  human-in-the-loop:
    remote: human-in-the-loop
    url: https://github.com/run-llama/template-workflow-human-in-the-loop.git
    branch: main
    version: 0.1.0
  invoice-extraction:
    remote: invoice-extraction
    url: https://github.com/run-llama/template-workflow-invoice-extraction.git
    branch: main
    version: 0.1.0
  rag:
    remote: rag
    url: https://github.com/run-llama/template-workflow-rag.git
    branch: main
    version: 0.1.0
  web-scraping:
    remote: web-scraping
    url: https://github.com/run-llama/template-workflow-web-scraping.git
    branch: main
    version: 0.1.0
