# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("ChatSession",)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime


@dataclasses.dataclass()
class ChatSession:
    id: int
    session_id: str
    message_role: str
    content: str | None
    created_at: datetime.datetime | None
