VERBS = [
    "thinking",
    "pondering",
    "overclocking brain",
    "debugging thoughts",
    "reasoning",
    "speculating",
    "daydreaming",
    "brainstorming",
    "conceptualizing",
    "plotting",
    "calculating",
    "theorizing",
    "ruminating",
    "processing",
    "scheming",
    "optimizing ideas",
    "looping on it",
    "hashing it out",
    "context switching",
    "garbage collecting memories",
    "refactoring thoughts",
    "bootstrapping plan",
    "compiling theories",
    "updating beliefs",
    "buffering",
]
